config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
end

app/models/article.rb
# Article model
class Article < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :comments

  self.per_page = 5

  validates :title, :content, :category, :completed_on, :user, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  accepts_nested_attributes_for :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
# User class
class User < ActiveRecord::Base
  has_many :articles
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.find_by(email: data['email'])

    unless user
      user = User.create(
        name: data['name'],
        email: data['email'],
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/articles_controller.rb
# Articles Controller
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_articles
  expose(:articles)
  expose(:paginated_articles) { articles.order('completed_on DESC').page(params[:page]) }
  expose(:article, attributes: :article_params)
  expose(:comments) { article.comments }
  expose(:comment) { Comment.new }

  def create
    article.user = current_user
    if article.save
      redirect_to article
    else
      render 'new'
    end
  end

  def update
    article.save
    redirect_to article
  end

  private

  def find_articles
    self.articles = Category.find(params[:category_id]).articles if params[:category_id]
  end

  def article_params
    params.require(:article).permit(:title, :content, :category_id, :completed_on)
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comments_params)
    @comment.article_id=params[:article_id]
    @comment.save
  end

  def show
  end

  private

  def comments_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  class MarkdownRenderer < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(:line_numbers => :table)
    end
  end

  def markdown(text)
    rndr = MarkdownRenderer.new(hard_wrap: true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :strikethrough => true,
      :lax_html_blocks => true,
      :superscript => true
    }
    markdown_to_html = Redcarpet::Markdown.new(rndr, options)
    markdown_to_html.render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def formatted_date(date)
    date.strftime("%b %Y")
  end

  def colorize(category)
    colors = {"reading" => "red", "coding" => "blue"}
    colors[category]
  end
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.slim
=simple_form_for article do |a|
  =a.input :title
  =a.input :content
  =a.input :completed_on
  =a.association :category
  =a.button :submit

app/views/articles/edit.html.slim
h1 Edit post 
=render 'form'

app/views/articles/index.html.slim
-paginated_articles.each do |article|
  .article  class="#{colorize(article.category.name)}"
    h1=link_to article.title, article_path(article)
    p=article.content
    p.footer Accomplished in #{formatted_date(article.completed_on)}
=will_paginate paginated_articles, renderer: BootstrapPagination::Rails

app/views/articles/new.html.slim
h1 Add new article
=render 'form'

app/views/articles/show.html.slim
h1=article.title
p=markdown(article.content)
hr
-if comments.any?
  h2 Comments
  =render comments


-if user_signed_in?
  =render 'comments/form'
-else
  p Log in to add new comment

app/views/comments/_comment.html.slim
p=comment.content
=comment.created_at

app/views/comments/_form.html.slim
p Comment form
=simple_form_for comment, url: article_comments_path(article) do |c|
  =c.input :content
  =c.button :submit

app/views/comments/create.html.slim
h1 Comments#create
p Find me in app/views/comments/create.html.slim

=console

app/views/comments/show.html.slim
h1 Comments#show
p Find me in app/views/comments/show.html.slim

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default
  .navbar-header
    button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to 'Learning Timeline', root_path, class: 'navbar-brand'
  .collapse.navbar-collapse
    ul.nav.navbar-nav.navbar-right
      li=link_to t('articles')
      li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            =t('categories')
            span.caret
          ul.dropdown-menu role="menu" 
            -Category.all.each do |c|
              li
                =link_to c.name.upcase, root_path(category_id: c.id)
      -if user_signed_in?
        li=link_to 'New article', new_article_path
        li=link_to 'LOGOUT', destroy_user_session_path, method: :delete
            

app/views/layouts/_navigation_links.html.slim
li=link_to 'asdf'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Timeline'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Timeline'}"
    == stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Open+Sans:400,800,300&subset=latin,latin-ext', :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    .container-fluid.
      header
        == render 'layouts/navigation'
      main[role="main"]
        .text-center
          == render 'layouts/messages'
          == yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>